---

DIR_byteMap: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/bytearray_HapMapGenMapGRC38_exHDGPmyMask/


list_suffix: ["statsIndvPop"]
#list_suffix: ["statsFocalPop_txt", "MWUpbs_txt", "statsIndvPop_txt", "perSNVpbs_txt"]

superPop:
    AMH:
        AMR: inputFile/AMR.shortIDs
    ARC:
        ARC: inputFile/ARC.shortIDs


windowSize: 2000

stepSize: 2000

numBatch: 10

list_numSamples_indicator: [1]


VCF:
    AMH:
        chr7: /net/eichler/vol27/projects/human_diversity/nobackups/HGDP_highCov/VCFs_bySangerInstitute_HardFilter/hgdp_wgs.20190516.full.chr7.myHGDPmask.wAA.vcf.gz
    ARC:
        chr7: /net/eichler/vol27/projects/human_diversity/nobackups/1KG_highCov/snpAD_hg38wDecoy/final_mergedVCF_HGDPmask/chr7.snpAD.snpAD.myHGDPmask.reorder.wAA.vcf.gz
